"""Add guild nicknames

Revision ID: 97fa1b4701f2
Revises: bcdcae2b73e4
Create Date: 2020-03-02 02:25:30.270108

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '97fa1b4701f2'
down_revision = 'bcdcae2b73e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guilds',
    sa.Column('discord_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String()),
    sa.PrimaryKeyConstraint('discord_id')
    )
    op.create_table('guild_members',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.discord_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.discord_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'guild_id', 'nickname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guild_members')
    op.drop_table('guilds')
    # ### end Alembic commands ###
